title: UCR Research Computing
description: "Empowering UCRs research community with advanced computing resources, training, and support."
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag