title: UCR Research Computing
description: "Empowering UCR's research community with advanced computing resources, training, and support."
remote_theme: pages-themes/cayman@v0.2.0

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag