title: UCR Research Computing
description: "Empowering UCRs research community with advanced computing resources, training, and support."
remote_theme: pages-themes/minimal@v0.2.0

sidebar:
  - about.md
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme