title: UCR Research Computing
description: "Empowering UCRs research community with advanced computing resources, training, and support."
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

sidebar:
  - about
  - label: Computing Resources
    children:
      - hpcc
      - ursa-major
      - cris-luster
      - can-cluster
      - nautilus
      - gcp-aws-edp
      - gcp-aws-cloud-credits
  - label: Research Data Storage
    children:
      - label: Cloud-Based Storage Solutions
        children:
          - google-drive
          - gcs-aws-s3
      - label: High-Performance Computing Storage
        children:
          - hpcc-gpfs
      - label: Special-Purpose Storage Solutions
        children:
          - ceph-secure-research-storage
          - dryad
          - crashplan
  - label: Services
    children:
      - High-Performance Computing
      - Cloud Services
      - Data Analytics
      - Secure Data Management      
  - label: Training & Development
    children:
      - Workshops & Webinars
      - Online Courses
      - Documentation & Guides
  - Policies & Compliance
  - Support
  - Success Stories
  - Contact Us



# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme