title: UCR Research Computing
description: "Empowering UCRs research community with advanced computing resources, training, and support."
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

sidebar:
  - about
  - label: Computing Resources
    children:
      - hpcc
      - ursa-major
      - cris-luster
      - can-cluster
      - nautilus
      - gcp-aws-edp
      - gcp-aws-cloud-credits
  - label: Research Data Storage
    children:
      - label: Cloud-Based Storage Solutions
        children:
          - google-drive
          - gcs-aws-s3
      - label: High-Performance Computing Storage
        children:
          - hpcc-gpfs
      - label: Special-Purpose Storage Solutions
        children:
          - ceph-secure-research-storage
          - dryad
          - crashplan
  - label: Research Support Services
    children:
      - research-computing-consultation
      - software-and-application-support
      - computing-and-research-infrastructure-support
      - grant-collaboration-and-innovation
      - supporting-research-security
      - optimizing-research-environments 
  - label: Training
    children:
      - workshops-and-webinars
      - online-courses
      - documentation-and-guides
  - policies-and-compliance
  - success-stories
  - contact-us



# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme