title: UCR Research Computing
description: "Empowering UCRs research community with advanced computing resources, training, and support."
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

search_enabled: true

sidebar:
  - label: Computing
    children:
      - hpcc
      - ursa-major
      - nsf-access
      - nautilus
      - nsf-osg
      - gcp-aws-edp
      - gcp-aws-cloud-credits
  - label: Data Storage
    children:
      - storage-overview
      - ursa-major-storage
      - google-drive
      - ursa-major-data
      - gcs-aws-s3
      - hpcc-gpfs
      - ceph-secure-research-storage
      - dryad
      - backup
  - label: Support
    children:
      - research-computing-consultation
      - software-and-application-support
      - computing-and-research-infrastructure-support
      - grant-collaboration-and-innovation
      - optimizing-research-environments 
  - label: Training
    children:
      - workshops-and-webinars
      - online-courses
      - documentation-and-guides
  - cost-models
  - research-security
  - policies
  - about
  - success-stories
  - contact-us



# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme